name: Build and test

on: [push, pull_request]

jobs:
  build_test:
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python: ["3.8", "3.9", "3.10", "3.11"]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        make requirements
    - name: Static analysis
      if: "matrix.python == '3.8'"
      run: |
        make check
    - name: Build packages
      if: "matrix.os != 'windows-latest'"
      run: |
        make package
    - name: Build packages (Windows)
      if: "matrix.os == 'windows-latest'"
      run: |
        cl /c "what_url/ada.cpp" /std:c++17 /Fo "what_url/ada.o"
        python -m build --no-isolation
    - name: Run tests
      run: |
        pip install -e .
        make coverage
    - name: Build docs with sphinx
      if: "matrix.python == '3.8'"
      run: |
        make docs
    - name: Upload packages
      uses: actions/upload-artifact@v3
      with:
        name: what-url-packages
        path: dist/*
